name: ci-backend

# Ensure the workflow runs on schedule (Sunday at 0:00) and on push to the main branch
on:
  pull_request:
    branches:
      - main
    paths:
    - 'frontend/**'
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:

#Use a matrix strategy to use Node.js versions 16.x and 18.x
jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      # Check out the code from the repository.
      - uses: actions/checkout@v3

      # Set up a Node.js environment using the specified node version.
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

  test:
      needs: [install_dependencies] 
      - name: Run tests
        run: pipenv run test

  lint:
      needs: [install_dependencies] 
      - name: Run linting
        run: pipenv run lint

  build:
    needs: [test,lint]  
    - run: cd frontend && npm run build