name: ci-frontend

on:
  pull_request:
    branches:
      - main
    # paths:
    #   - 'frontend/**'
  workflow_dispatch: # Manual trigger using the workflow_dispatch event

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code from the repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Use Node.js ${{ matrix.node-version }} and run tests
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - working-directory: ./frontend
        run: npm run test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code from the repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Use Node.js ${{ matrix.node-version }} and run lint
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - working-directory: frontend
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - name: Check out the code from the repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }} and run build
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Run build
        working-directory: frontend
        run: npm run build
